### ISSUE TITLE
Why this library work only with internet connection?

### ISSUE THREAD

**Issue by sebamena** [Krupen/AutoplayVideos#41] opened 2017-10-20 13:02 UTC
I spend a lot of time searching the issue in my code and the problem was the internet connection.

With internet all work fine, but without connection all work bad.

**Comment by sebamena** [comment] 2017-10-20 13:15
java.lang.NullPointerException at com.allattentionhere.autoplayvideos.AAH_CustomVideoView.onDetachedFromWindow(AAH_CustomVideoView.java:159)

**Comment by Krupen** [comment] 2017-10-21 07:18
Hi @sebamena , I just checked and the sample app works fine when internet is off. 
Are you using the latest version of library (v0.1.7)? 
If you are using latest version, can you help me reproduce this crash so that I can resolve it.

**Comment by sebamena** [comment] 2017-10-21 12:15
I tried to load only local videos on the itemviews.
When item is clicked, the camera is open and take the video, then load into the videoview.
With Internet works and witohout no.

**Comment by Krupen** [comment] 2017-10-21 12:32
Yes, the local videos were not playing when offline. Added support for that and released it, check out version 0.1.8
Thanks for raising the issue.

**Comment by Krupen** [comment] 2017-11-02 09:37
Hope the issue is fixed. Closing this for now, feel free to re-open if not solved.

**Closed by Krupen** 2017-11-02 09:37 UTC
