### ISSUE TITLE
Hi,, I have working on autoplay video using this code but i am facing issue. when i am scrolling my view position are changed automatically. Here is my adapter class.

### ISSUE THREAD

**Issue by vandanabpatel** [Krupen/AutoplayVideos#12] opened 2017-03-24 15:58 UTC
public class FeedAdapter extends AAH_VideosAdapter {
    String TAG = getClass().getSimpleName();
    Activity activity;
    Globals globals;

    private static final int SECOND_MILLIS = 1000;
    private static final int MINUTE_MILLIS = 60 * SECOND_MILLIS;
    private static final int HOUR_MILLIS = 60 * MINUTE_MILLIS;
    private static final int DAY_MILLIS = 24 * HOUR_MILLIS;

    ArrayList<FeedModel> feedList;

    public class MyViewHolder extends AAH_CustomViewHolder {
        TextView TxtPost, TxtLike, TxtComment, TxtName, TxtTime;
        ImageView ImgPost, ImgLike, ImgComment;
        CircularImageView ImgFphoto;
        AAH_VideoImage view_video;

        public MyViewHolder(View x) {
            super(x);
            TxtPost = ButterKnife.findById(x, R.id.TxtPost);
            TxtLike = ButterKnife.findById(x, R.id.TxtLike);
            TxtComment = ButterKnife.findById(x, R.id.TxtComment);
            TxtName = ButterKnife.findById(x, R.id.TxtName);
            TxtTime = ButterKnife.findById(x, R.id.TxtTime);
            ImgPost = ButterKnife.findById(x, R.id.ImgPost);
            ImgLike = ButterKnife.findById(x, R.id.ImgLike);
            ImgComment = ButterKnife.findById(x, R.id.ImgComment);
            ImgFphoto = ButterKnife.findById(x, R.id.ImgFphoto);
            view_video = ButterKnife.findById(x, R.id.view_video);
        }
    }

    public FeedAdapter(Activity activity, ArrayList<FeedModel> feedList) {
        this.activity = activity;
        this.feedList = feedList;
        feedList.get(0).setFile("");
        globals = ((Globals) activity.getApplicationContext());
    }

    @Override
    public AAH_CustomViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(parent.getContext()).inflate(R.layout.feed_layout, parent, false);
        return new MyViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(final AAH_CustomViewHolder holder, int position) {
        final FeedModel item = feedList.get(position);

        ((MyViewHolder) holder).TxtName.setText(item.getName());
        ((MyViewHolder) holder).TxtPost.setText(item.getPost());
        ((MyViewHolder) holder).TxtLike.setText(item.getLike_count());
        ((MyViewHolder) holder).TxtComment.setText(item.getComment_count());

        ((MyViewHolder) holder).ImgLike.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                int likecount;
                if (item.getIs_like() == 1) {
                    item.setIs_like(0);
                    likecount = Integer.parseInt(item.getLike_count());
                    item.setLike_count(String.valueOf(likecount - 1));
                    ((MyViewHolder) holder).ImgLike.setImageResource(R.drawable.like);
                    likeUnlikepost(item.getPost_id());
                    notifyDataSetChanged();
                } else {
                    item.setIs_like(1);
                    likecount = Integer.parseInt(item.getLike_count());
                    item.setLike_count(String.valueOf(likecount + 1));
                    ((MyViewHolder) holder).ImgLike.setImageResource(R.drawable.liked);
                    likeUnlikepost(item.getPost_id());
                    notifyDataSetChanged();
                }
            }
        });

        //load image into imageview
        if (item.getPhoto() != null && !item.getPhoto().isEmpty()) {
            Picasso.with(activity).load(Constant.URL_USERPHOTO + item.getPhoto().replaceAll(" ", "%20")).into(((MyViewHolder) holder).ImgFphoto);
        }

        // time
        if (item.getCreated() != null) {
            long timeInMilliseconds = 0;
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            try {
                Date mDate = sdf.parse(item.getCreated());
                timeInMilliseconds = mDate.getTime();
                String Timeago = getTimeAgo(timeInMilliseconds);
                ((MyViewHolder) holder).TxtTime.setText(Timeago);
            } catch (ParseException e) {
                e.printStackTrace();
            }
        }

        if (item.getPost_type().matches("1")) {
            // text only
        } else if (item.getPost_type().matches("2")) {
            // image only
            holder.setImageUrl(Constant.URL_POSTFILE + item.getFile().replaceAll(" ", "%20"));
        } else {
            // video only
            Log.e("Video", "URL : " + Constant.URL_POSTFILE + item.getFile().replaceAll(" ", "%20"));
            holder.setImageUrl(Constant.URL_POSTFILE_THUMBNAIL + item.getThumbnail().replaceAll(" ", "%20"));
            holder.setVideoUrl(Constant.URL_POSTFILE + item.getFile().replaceAll(" ", "%20"));
        }

        if (holder.getImageUrl() != null && holder.getImageUrl().length() > 0) {
            Picasso.with(activity).load(holder.getImageUrl()).into(holder.getAAH_ImageView());
        }
    }

    @Override
    public int getItemCount() {
        return feedList.size();
    }

    @Override
    public int getItemViewType(int position) {
        return 0;
    }
}

Here, my other property remaining same just photo and video's positon are changed. when i am scrolling.

**Comment by Krupen** [comment] 2017-03-25 06:09
I am unable to find any bug in your code, if you could share project or share just enough code to reproduce this bug would be helpful.

**Comment by vandanabpatel** [comment] 2017-03-25 12:56
I have make service call it will return JSONArray
it will return file name
So, i have parse into Arraylist <Model>feedList and fill into AAH_CustomRecyclerView

FeedAdapter mAdapter = new FeedAdapter(getActivity(), feedList);
                            mLayoutManager = new LinearLayoutManager(getActivity());

                            rv_post.setLayoutManager(mLayoutManager);
                            rv_post.setItemAnimator(new DefaultItemAnimator());
                            rv_post.setActivity(getActivity());
                            rv_post.setAdapter(mAdapter);
                            rv_post.smoothScrollBy(0, 1);
                            rv_post.smoothScrollBy(0, -1);

and above are my adapter class when i am scrolling AAH_CustomRecyclerView other item are remain same at their position but only video and image are changed their position

**Comment by Krupen** [comment] 2017-03-29 07:05
I am not sure if this is the solution as I can't reproduce it. But this kind of behaviour happens when there is no `else` for every `if` in `onBindViewHolder` method of Recyclerview.

Recyclerview re-uses the views so if you don't set every view item, it will re-use the previously set item and it would seem that positions are changed.

**Comment by Krupen** [comment] 2017-04-07 11:12
Closing this issue for now, feel free to reopen if it's not solved.

**Closed by Krupen** 2017-04-07 11:12 UTC
